# Project information
site_name: Portfolio of Nusrat Jahan Papri
# defeine TOC or order of website-

# nav:
#   - Home: index.md
#   - Education:
#     - My Education: Education.md
#     - My Skills: myskills.md 
#   - Skills : 
#     - Basic Arduino: basic-arduino.md
#     - Programming Skill: 
#   - Projects: 
#   - Achievements: 
nav:
  - Home: index.md
  - Education: Education.md 
      #  - My education: Education.md 
  #- Research Experience: research-paper.md
  - My Skills: 
     - Basic Arduino: basic-arduino.md
     - EEE Hardware and Software: 
        - Electrical Circuit Simulation: circuit-simulation.md
        - Numerical Analysis: numerical-matlab.md
        - Transformer Design: transformer-design.md
     - Programming Language: CplusPlus.md
  #- Training and Working Experience: training-working.md  
  - Projects: 
     - IOT based Health Monitoring System: iot-based-health-monitoring.md
     - Ultrasonic Distance Measurement: ultrasonic-distance-measurement.md
     - Electronic Mosquito Repellent: Mosquito-repellent-ckt.md
  - Achievements: achievements.md
  - Course and Certification: course-and-certification.md
   # -  Course and Certification: course-and-certification.md

site_author: Nusrat Jahan Papri
site_description: >-
  



# Repository
# repo_name: ramiz-moktader/
# repo_url: https://github.com/ramiz-moktader/

# Configuration
theme:
  name: material
  favicon: img/NP-logo.ico       
  logo: images/NP-logo.png

  features:
    
    - content.code.copy
    # - content.tabs.link
    # - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    # - navigation.indexes
    # # - navigation.instant
    # # - navigation.instant.prefetch
    # # - navigation.instant.progress
    # # - navigation.prune
    # - navigation.sections
    # # - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.top
    # - navigation.tracking
    # - search.highlight
    # - search.share
    # - search.suggest
    # - toc.follow
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    # - toc.integrate

  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime    
  # logo: PyTorch_logo_icon.svg
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/nusrat008/
    # - icon: fontawesome/brands/twitter
    #   link: https://github.com/ramiz-moktader/
    # - icon: fontawesome/brands/linkedin
    #   link: https://github.com/ramiz-moktader/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/nusrat-papri 

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - toc:
      permalink: true
  - attr_list
  - md_in_html
extra_css:
  - stylesheets/extra.css
  
plugins:
  - search
# extra:
#   generator: false
copyright: |
  &copy; 2024 <a href="https://nusrat008.github.io/Portfolio/"  target="_blank" rel="noopener"> Nusrat Jahan Papri</a>